### ISSUE TITLE
Recurring expenses?

### ISSUE THREAD

**Issue by jeremymeyers** [bertvandepoel/tabby#11]
Hello! I'm trying to replace Splitwise for keeping track of expenses between me and my partner, and was curious whether tabby can handle recurring expenses?

**Comment by bertvandepoel** [comment]
Hi Jeremy! It was my annoyance with Splitwise that made me create Tabby, so I totally get why you're trying to get it replaced. Currently I don't have any code in place to automatically add monthly expenses. I assume that's what you are looking for? I could however patch it in (I'm fairly willing to write code for features users may require). Could you maybe give me some examples of how you would want to use this feature? That way I can better imagine what kind of interface is required. Would terms like monthly or weekly make sense? Is it a set cost? Should it just be added whenever a specific day of the month/week passes? Those are the kinds of questions I have about this feature.

Based on the timing of your issue, I presume you're in the Americas (and probably in the US). Currently Tabby somewhat naively presumes Euros and IBANs (international standard for bank account numbers). I was discussing with another potential user in #7 what I should do to make it more adapted to international use. I can easily add an option to configure the currency during installation, but I'm not quite sure what kind of number people over there use to perform bank transfers and whether it has a standard length of some kind.

**Comment by jeremymeyers** [comment]
Well, for example, if I pay $50/month for Netflix and want to split that 50/50 with my partner, i would like to be able to enter it once, say "repeat monthly" and have it just do it. I would suggest adding a "starting on x date" option so people can enter the specific day of the month from which they would like to start counting.

Cannot speak to the second part, unfortunately.  A lot of people i know will use a middleman app like Paypal or Venmo to transfer money around, rather than directly through banks.

**Comment by bertvandepoel** [comment]
Sorry you haven't been hearing from me. Even though I've been quiet, I've actually been quite busy implementing your requested feature and some other extras during my weekends off. It turned out to be more of a challenge, and not the easiest thing to test, but I've now added recurring expenses! I hope you're still interested in trying out Tabby, and feel free to let me know if the feature works like you expected.

I've also added support for different currency symbols on installation BTW. That's probably relevant for you as well!
